### ISSUE TITLE
[Issue] Cannot Open .bbmodel files on iOS

### ISSUE THREAD

**Issue by Kas-tle** [JannisX11/blockbench#1128]
## Detailed description of your issue

The file picker on iOS does not allow the user to open bbmodel files when opening a model. This effectively cripples the web app for iOS users. Best I can tell, only files with the extension JSON are allowed. I know this is definitely possible, as the minimal html `<input type="file">` creates a file submission form which allows for the upload of any file type.

## Model format in which the issue occurs

The issue occurs for all model formats when the extension bbmodel is used.

## Blockbench variant (Website / PWA / Program)

The issue occurs on both the website and PWA variants.

## Operating System

iOS 15.0.2

**Comment by Overdrive2901** [comment]
Same for me and I am using Android 12, it worked at first then it just stoped working.

**Comment by JannisX11** [comment]
> Same for me and I am using Android 12, it worked at first then it just stoped working.

It works for me on Android. Make sure the file is named `model.bbmodel` and not `model.bbmodel.txt`.

Unfortunately Safari still does not fully support file extensions (https://caniuse.com/input-file-accept) so there is not much I can do.

**Comment by leroke** [comment]
Meu problema é no Android 11, quando eu uso a opção "abrir modelo" ele diz que não tem memória o suficiente sendo que já liberei uma quantidade absurda de memória no dispositivo, mas mesmo assim ele não funciona.

**Comment by pedestriantactics** [comment]
> > Same for me and I am using Android 12, it worked at first then it just stoped working.
> 
> It works for me on Android. Make sure the file is named `model.bbmodel` and not `model.bbmodel.txt`.
> 
> Unfortunately Safari still does not fully support file extensions (https://caniuse.com/input-file-accept) so there is not much I can do.

How come import works then? If I start a new model I can then import my blockbench model from iOS files using the import button.

**Comment by JannisX11** [comment]
That's a very good point. The difference is that it only passes one extension to the input element. I'll try something to work around this.

**Comment by JannisX11** [comment]
Fixed in 4.2.2.

**Comment by TheASEStefan** [comment]
Nah it still doesn't work. The picker doesn't let me pick any of my models. They are just grayed out.
