### ISSUE TITLE
[Issue] .java exporter does not export bone with loose cubes

### ISSUE THREAD

**Issue by scrouthtv** [JannisX11/blockbench#637]
I am running Blockbench 3.5.2. During startup these two errors occured although I think they don't cause my problem:
```
DevTools failed to parse SourceMap: file:///C:/Users/lenni/AppData/Local/Programs/Blockbench/resources/app.asar/lib/gif.js.map
DevTools failed to parse SourceMap: file:///C:/Users/lenni/AppData/Local/Programs/Blockbench/resources/app.asar/lib/VuePrismEditor.umd.min.js.map
``` 

I created a simple model:
![image](https://user-images.githubusercontent.com/23227405/82360652-fb511680-9a09-11ea-92c4-22cbbfe3d984.png)
which basically consists of a white cube, added a texture and clicked on File > Export > Export Java Entity.

This is a Modded Entity project.

## Now to my problem
I tried exporting the model to a `java` file (v1.12.2) but I simply got a more or less empty file - `test.java`:
```
// Made with Blockbench 3.5.2
// Exported for Minecraft version 1.12
// Paste this class into your mod and generate all required imports


public class heatpipe_base extends ModelBase {
	

	public heatpipe_base() {
		textureWidth = 32;
		textureHeight = 32;

		
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}
```

Now the weird thing is, on a different pc with Blockbench `3.4.2` exporting the very same model file as java works as expected and produces a good file.

I am running Blockbench Desktop (3.5.2 is Desktop installed while 3.4.2 is Portable) on Windows 10.

**Comment by JannisX11** [comment]
All cubes in entity models need to be inside a bone. This is still an issue since it should generate a bone for loose cubes, but if you correctly add your cubes to bones, you won't come across it.

**Comment by JannisX11** [comment]
Fixed in 3.5.3.

**Comment by scrouthtv** [comment]
Still not working for me:
![image](https://user-images.githubusercontent.com/23227405/87433430-979e3080-c5e9-11ea-8974-ac575e3cd2fc.png)
```
// Made with Blockbench 3.5.4
// Exported for Minecraft version 1.12
// Paste this class into your mod and generate all required imports


public class custom_model extends ModelBase {
	private final ModelRenderer bb_main;

	public custom_model() {
		textureWidth = 32;
		textureHeight = 32;

		bb_main = new ModelRenderer(this);
		bb_main.setRotationPoint(0.0F, 24.0F, 0.0F);
		
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		bb_main.render(f5);
	}

	public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
		modelRenderer.rotateAngleX = x;
		modelRenderer.rotateAngleY = y;
		modelRenderer.rotateAngleZ = z;
	}
}
```

I am running `v.3.5.4` on `Linux arch-desktop 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux`

**Comment by scrouthtv** [comment]
Here's the file
[armor.bbmodel.zip](https://github.com/JannisX11/blockbench/files/4919203/armor.bbmodel.zip)
@JannisX11

**Comment by JannisX11** [comment]
Check https://github.com/JannisX11/blockbench/issues/655
