### ISSUE TITLE
Unable to open the web version of blockbench

### ISSUE THREAD

**Issue by 123sws** [JannisX11/blockbench#843]
Since yesterday's version was updated, when I opened the web blockbench today, it continued to display an error. When I loaded the blockbench, I changed my browser, but still did not solve this problem
My mobile phone is Android
![-64af22ac410cfb3](https://user-images.githubusercontent.com/80188219/110229697-58409d80-7f46-11eb-9204-828718caffc6.jpg)

>

**Comment by JannisX11** [comment]
Please try and clear your browser cache.

**Comment by JannisX11** [comment]
Fixed in https://github.com/JannisX11/blockbench/commit/232666b03c321e8df92863e279c84d8b85e2049c.

**Comment by 123sws** [comment]
Hey, it still doesn't work, even if I clear the browser data
